"""inital

Revision ID: 57b22e458fe4
Revises: 
Create Date: 2024-01-30 12:11:12.899814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b22e458fe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_puzzles_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upattempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_upattempts_puzzle_id_puzzles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_upattempts_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('clue', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('column_index', sa.Integer(), nullable=True),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_words_puzzle_id_puzzles')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('column_index', sa.Integer(), nullable=True),
    sa.Column('upattempt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upattempt_id'], ['upattempts.id'], name=op.f('fk_guesses_upattempt_id_upattempts')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guesses')
    op.drop_table('words')
    op.drop_table('upattempts')
    op.drop_table('puzzles')
    op.drop_table('users')
    # ### end Alembic commands ###
